### PR TITLE
fix(exec-script-tmp): uses tmp and mounts volume instead of creating locally

### LINKED ISSUE #49: Remove temp devlab.sh immediately upon execution
The feature added in 3.3.3 which creates a temp `devlab.sh` to run the commands from the task currently waits until ALL execution is finished to remove the file. This means that if the task errors the file doesn't get removed.

Need to have the `devlab.sh` file removed immediately after it is executed to prevent issues with overwrites/permissions or accidentally committing the file to version control.

### PR DESCRIPTION
**Pull request by Fluidbyte**
Instead of creating local `devlab.sh` this will create in the OS's temp dir, mount, and execute.

Why this wasn't done initially is on me; I just defaulted to `/tmp` but this caused issues on Mac and Circle. Now the temp directory is determined by the `/src/tempdir` module which will allow either a custom setting via the `DEVLAB_TMP` environment variable, or will try to determine the best temp directory to use.

Tested both on my linux server and on my local Mac.

Closes #49 by no longer storing this exec script local.

### CODE REVIEW

**Comment by Fluidbyte** [comment]
Looks like this approach is still causing issues:

```
docker: Error response from daemon: Mounts denied: ces for more info.
.
folders/3c/3fxzr4l11l353xd26xg4psnm0000gn/T
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespa.
ERRO[0000] error getting events from daemon: net/http: request canceled 
```

**Comment by Fluidbyte** [comment]
Mac's default `TMPDIR` is `/var/folders/...` which is not a shared folder with the docker client. I don't like the idea of forcing users to share `/var`, so the latest fix has multiple approaches to fixing this issue.

1. It will check for a (user defined) `DEVLAB_TMP` which will allow a user to explicitly set this path
2. It will check for `TEMPDIR` (the Mac designation) and use `/tmp`
3. If all else fails it uses [`os-tmpdir`](https://github.com/sindresorhus/os-tmpdir) to try to get the temp location

**Comment by stephen-ta** [comment]
@Fluidbyte I pulled this branch and ran `npm run test` on my local Mac. Two tests failed due to it using `/var/folders/...` but then I setup `export DEVLAB_TMP=/tmp` in my `~/.profile` and ran `npm run test` again, and all tests passed!

File: src/index.js [hunk 1]
```diff
@@ -11,7 +11,12 @@ const proc = require('./proc')
 const output = require('./output')
 const utils = require('./utils')
 
-Promise.promisifyAll(fs)
+/* istanbul ignore next: very os-specific crap */
+const tmpdir = process.env.DEVLAB_TMP
+      // If override set, use that
+      ? process.env.DEVLAB_TMP
+      // If MacOS TEMPDIR, use /tmp, else try to find using os-tmpdir
+      : process.env.TEMPDIR ? '/tmp' : require('os-tmpdir')()
```
Comment (stephen-ta) [inline src/index.js]: 😎

**Comment by Fluidbyte** [comment]
I'm not really happy with this approach because it seems to be hit or miss. It worked fine for me just letting it default to `/tmp`, but seems like this could vary on Mac's and having to set an env var (for anything more than customization, fringe cases) seems hacky.

**Comment by Fluidbyte** [comment]
Latest commit creates a module which will (I think) do a better job. It's process is:

1. If `DEVLAB_TMP` is specified, check if writeable, use that
2. If not 1, Check if `/tmp` is writable, use that
3. If not 2, Check if `os-tmpdir` suggests a writeable dir, use that
4. If all else fails, error with notification about manually specifying `DEVLAB_TMP`, exit

Seems to work everywhere I've tested. Would love some local testing both with and without `DEVLAB_TMP` set. 

**The best way to check this is with `npm run e2e` which will run end-to-end tests.**

**Comment by Fluidbyte** [comment]
The latest approach seems to be checking out where I've tested it. If I can get a couple/few people to check it out it would be appreciated.

1. Clone the repo and checkout `fix/exec-script-tmp`, run `npm install`
2. `cd test/project` and run `../../index.js env` and ensure it works
3. `export DEVLAB_TMP=/tmp`then run `../../index.js env` and ensure that works
4. Try setting `DEVLAB_TMP` to another location like `/var` and test

If the above look good give me a nod and once I'll get it merged and published.

File: README.md [hunk 2]
```diff
@@ -25,6 +25,8 @@ npm install devlab -g
 
 *Obvious Note: You need to have [Docker](https://www.docker.com/) installed as well.*
 
+**Important Note**: In order to run the tasks, Devlab creates a temp file (`devlab.sh`). The tool will do it's best to determine the best location (usually `/tmp`), but this can be explicitly set by specifying the environment variable `DEVLAB_TMP`.
```
Comment (davezuko) [inline README.md]: `it's` -> `its`

File: src/tempdir.js [hunk 3]
```diff
@@ -0,0 +1,39 @@
...
+  }
+
+  // Check our options...
+  if (process.env.DEVLAB_TMP && isWriteable(process.env.DEVLAB_TMP)) {
+    // Use user-specified DEVLAB_TMP
+    return process.env.DEVLAB_TMP
+  } else if (isWriteable('/tmp')) {
+    // Use (most common) /tmp
+    return '/tmp'
+  } else if (isWriteable(require('os-tmpdir')())) {
```
Comment (davezuko) [inline src/tempdir.js]: Should this be preferred over `/tmp`?

Comment (Fluidbyte) [inline src/tempdir.js]: You would think that, the problem is it tries to use `TMPDIR` on Mac which is `/var/folders/...` and is not shared with Docker on install. In _most_ cases `/tmp` should work fine and is how you would expect an application to work on *nix systems. This basically is just used when all else fails.

Comment (davezuko) [inline src/tempdir.js]: Ah ok. I do remember having odd trouble with `os-tmpdir` in the past, which seemed silly since the whole point of that module is that it should _just work_. Thanks for the explanation.

Comment (Fluidbyte) [inline src/tempdir.js]: Yeah, this really is the use-case for weird, non-standard setups or Windows.

File: README.md (hunk 2 above)
Comment (Fluidbyte) [inline README.md]: changed, just not showing up here...

**Comment by stephen-ta** [comment]
I pulled the latest and ran `npm run test` which passed tests. I commented out `export DEVLAB_TMP=/tmp` and ran again, which also passed tests now. So this appears to work for me on my local Mac, yet fwiw I tried the QA Test instructions and couldn't get it working and also `npm run e2e` didn't all appear to work. Let me know if you want to screenshare and try this together.

**Comment by Fluidbyte** [comment]
Checked out ^^^. All good.

**Comment by levithomason** [comment]
Sorry for the delay, this is on my list for testing.

**Comment by levithomason** [comment]
2 failures on a fresh pull and deps install. Output trimmed to relevant parts.  LMK what I can to help:

```
#----------------------------------------------
# basic multiple: Runs multiple tasks
# devlab env test
#----------------------------------------------

> devlab-demo@1.0.0 test /DevLab/test/project
> mocha ./test --recursive

sh: mocha: not found

#----------------------------------------------
# ignore disable: Passes because service is not disabled for all tasks
# devlab env redis:disable
#----------------------------------------------

Error: Cannot find module 'redis'
    at Object.<anonymous> (/DevLab/test/project/scripts/connect.js:1:77)

#----------------------------------------------
# TEST RESULTS: 2 failures
# basic multiple, ignore disable
#----------------------------------------------
```

Just to be sure, ran it again with fresh deps and got the same results.

**Comment by Fluidbyte** [comment]
`cd test/project/ && node ../../index.js install`

That will install department in the test project, then `cd ../../ && npm run e2e`

**Comment by levithomason** [comment]
hang tight

**Comment by levithomason** [comment]
🎉 
```
#----------------------------------------------
# TEST RESULTS: 0 failures
#----------------------------------------------
```

**Comment by Fluidbyte** [comment]
:+1:
