### PR TITLE
fix(service-stop): run service stop as parallel spawn instead of detached

### LINKED ISSUE #54: Build up of containers eventually chokes system resources
After running several `lab` tasks throughout the day, the containers started by DevLab build up over time.  These eventually turn my fans into rocket ships and start choking my system:

<p align=center>
  
</p>

I find I have to restart docker periodically to reclaim system performance and settle my fans.  It would be grand if we could find a way to reliably kill off these containers after using them.

If we know they are running, can we spawn a child process to kill them instead of logging that they are still running?

### PR DESCRIPTION
**Pull request by Fluidbyte**
Closes #54

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -52,6 +52,19 @@ const instance = {
...
   },
   /**
+   * Stops services and resolves or rejects
+   * @returns {object} promise
+   */
+  stopServices: () => {
+    const servicesStopSpinner = output.spinner('Stopping services')
+    return services.stop()
+      .then(() => servicesStopSpinner.succeed())
+      .catch((err) => {
```
Comment (levithomason) [inline src/index.js]: Not sure of the flow, but this error is caught and never thrown or `rejected`.  Just heads up this promise chain will truck on with a resolved state.

File: test/src/services.spec.js [hunk 2]
```diff
@@ -49,7 +49,7 @@ describe('services', () => {
         })
     })
   })
-  describe('stop', () => {
+  xdescribe('stop', () => {
```
Comment (levithomason) [inline test/src/services.spec.js]: whoops!

Comment (Fluidbyte) [inline test/src/services.spec.js]: I left that because the test is broken right now, just wanted you to test it local

**Comment by levithomason** [comment]
Something in here has broken `lab --clean`:

```
⚠ These containers may not have exited correctly: dl_elasticsearch_HkMsXE23g, dl_postgres_HkMsXE23g, dl_mysql_HkMsXE23g, dl_aws-dynamodb_HkMsXE23g, dl_elasticmq_HkMsXE23g
⚠ You can attempt to remove these by running `lab --cleanup`
```

```
› lab --cleanup
Error response from daemon: No such container: d2685809eaad
✖ Command failed: docker stop d2685809eaad && docker rm d2685809eaad && docker stop 5c00ae10b9de && docker rm 5c00ae10b9de && docker stop 8f48c05402ec && docker rm 8f48c05402ec && docker stop c3bd672ab39c && docker rm c3bd672ab39c && docker stop 2fce2fcc3c6c && docker rm 2fce2fcc3c6c && docker stop 3f8f875efba2 && docker rm 3f8f875efba2 && docker stop 22351635bcf5 && docker rm 22351635bcf5 && docker stop 6a24d249c85a && docker rm 6a24d249c85a && docker stop 2e74db01ac12 && docker rm 2e74db01ac12 && docker stop 176d462fc284 && docker rm 176d462fc284 && docker stop 11bbb71b6544 && docker rm 11bbb71b6544 && docker stop 7c39dc411c16 && docker rm 7c39dc411c16 && docker stop 0e27efcbf357 && docker rm 0e27efcbf357 && docker stop 166a5f269bf4 && docker rm 166a5f269bf4 && docker stop d0b2ea7b99b0 && docker rm d0b2ea7b99b0 && docker stop 75b2c0ba44f3 && docker rm 75b2c0ba44f3
Error response from daemon: No such container: d2685809eaad
```

File: src/index.js (hunk 1 above)
Comment (Fluidbyte) [inline src/index.js]: Yep, that's the plan; don't throw anything, it will show the error and move on.

**Comment by Fluidbyte** [comment]
^ That means the container wasn't found in `docker ps -a`, that needs some re-work before I wrap this.

**Comment by levithomason** [comment]
Pushed the commit for better `--cleanup` output.  Whereas it was silent before:

File: src/services.js [hunk 3]
```diff
@@ -63,17 +64,27 @@ const services = {
...
-    _.pipe([
-      _.filter(_.test(/dl_/)),
-      _.map(svc => `docker stop ${svc} && docker rm ${svc}`),
-      _.join(' && '),
-      proc.runDetached
-    ])
-  )(services.running)
+  stop: () => {
+    const errors = []
+    return Promise.all(_.unless(
```
Comment (davezuko) [inline src/services.js]: I believe you can skip the `isEmpty` check, since if it's empty there will be nothing to filter/map over and thus it will resolve immediately.

Probably either consider that extraneous check or just return early if it's empty for cleanliness?
